name: Publish LSD Wizard SDK

on:
  # Publishing only happens when pushing to main branch is made
  push:
    branches: [ "main" ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Who am I?
        uses: npm whoami --registry https://registry.npmjs.org
      - run: npm publish --registry=https://npm.pkg.github.com/ --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}